Full table name used instead of alias
Mysql crashed on myspotsposted page because full table name was used instead of reference.

Error: SpotWeb v0.68.33.34 on PHP v8.0.12 crashed 42S22: 1054: Unknown column 'spotsposted.ouruserid' in 'where clause'